export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGiSTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/shop'
export const BASKET_ROUTE = '/basket'
export const DEVICE_ROUTE = '/device'
export const MAIN_PAGE_ROUTE = '/main'
